#!/usr/bin/env bash

set -o errexit

KOMOREBI_VERSION=0.1.0

COMMAND="${COMMAND:-date}"
PORT=${PORT:-1500}
HTTP_START="HTTP/1.1"
HTTP_GOOD="200 OK"
HTTP_BAD="500 Internal Error"
NETCAT_PACKAGE='netcat-openbsd'

echo "Initializing Komorebi..."

if which apt-get &>/dev/null; then
    if ! dpkg -s $NETCAT_PACKAGE &>/dev/null; then
        echo "Could not find the 'netcat' utility; trying to install"
        echo "First, updating apt repositories"
        apt-get update &>/dev/null
        echo "Now, installing '$NETCAT_PACKAGE'"
        apt-get -y install $NETCAT_PACKAGE &>/dev/null
    fi
fi

trap "exit" INT

echo "Starting Komorebi HTTP server on port ${PORT}"
echo "Command: '${COMMAND}'"

while true; do
    if eval $COMMAND &>/dev/null; then 
        RESP="${HTTP_START} ${HTTP_GOOD} \n\n "
    else
        RESP="${HTTP_START} ${HTTP_BAD} \n\n "
    fi
    echo -e "${RESP}" | nc -l "${PORT}"
done
